import { Icon, IconifyIcon, IconProps } from "@iconify/react";
import { ReactNode } from "react";

export type iconAsProp = IconifyIcon | ReactNode;
export type iconRN = Record<allRequiredIcons, ReactNode>;

export function Icon2RN({
  icon,
  ...props
}: IconProps | { icon: iconAsProp }): ReactNode {
  if (
    typeof icon === "string" ||
    (typeof icon === "object" && icon !== null && "body" in icon)
  ) {
    return <Icon {...props} icon={icon} />;
  }
  return icon;
}

const R_icons = [
  "settings",
  "widget",
  "lock",
  "unlock",
  "habitTracker",
  "pin",
  "sort",
  "show",
  "hide",
  "search",
  "checklist",
  "space",
  "bookmark",
  "reset",
  "edit",
  "delete_",
  "menu",
  "add",
  "note",
] as const;
export type allRequiredIcons = (typeof R_icons)[number];
export const requiredIcons: allRequiredIcons[] = [...R_icons];
export type iconData = Record<allRequiredIcons, iconAsProp>;

export function transformIcons<T extends Partial<iconData>>(
  iconObject: T,
  prefix: string | null = null,
  itemToReplace: string = "",
  replacementItem: string = ""
): T extends iconData ? iconRN : Partial<iconRN> {
  const transformed: Partial<iconRN> = {};

  for (const [name, val] of Object.entries(iconObject)) {
    let transformedVal: iconAsProp = val;
    if (typeof val === "string") {
      if (itemToReplace !== replacementItem) {
        transformedVal = val.replace(itemToReplace, replacementItem);
      }
      if (prefix) {
        transformedVal = `${prefix}:${transformedVal}`;
      }
    }
    transformed[name as allRequiredIcons] = (
      <Icon2RN className="theme-icons" icon={transformedVal} />
    );
  }

  return transformed as T extends iconData ? iconRN : Partial<iconRN>;
}

const solar_bold: Partial<iconRN> = {
  settings: "settings-bold",
  widget: "widget-add-bold",
  unlock: "lock-unlocked-bold",
  lock: "lock-bold",
  habitTracker: "calendar-mark-bold",
  pin: "pin-bold",
  sort: "sort-from-top-to-bottom-bold",
  reset: "refresh-bold",
  checklist: "checklist-minimalistic-bold",
  bookmark: "bookmark-bold",
  edit: "pen-new-square-bold",
  delete_: "trash-bin-trash-bold",
  menu: "hamburger-menu-bold",
  show: "eye-bold",
  hide: "eye-closed-bold",
  space: "planet-2-bold",
  add: "add-square-bold",
};
export const _ri_fill: iconRN = {
  settings: "settings-4-fill",
  widget: "apps-2-add-fill",
  lock: "lock-fill",
  unlock: "lock-unlock-fill",
  habitTracker: "calendar-check-fill",
  pin: "pushpin-fill",
  sort: "sort-desc",
  search: "search-2-fill",
  reset: "refresh-fill",
  checklist: "list-check-3",
  bookmark: "bookmark-fill",
  edit: "edit-2-fill",
  delete_: "delete-bin-fill",
  menu: "menu-fill",
  show: "eye-fill",
  hide: "eye-off-fill",
  space: "rocket-2-fill",
  add: "add-circle-fill",
  note: "booklet-fill",
};
export const ri_line = transformIcons(_ri_fill, "ri", "fill", "line");
export const ri_fill = transformIcons(_ri_fill, "ri");

export const SelectedIconPacks: Record<string, iconData> = {
  "Remix Icon Filled": ri_fill,
  "Remix Icon Line": ri_line,
  "material-symbols": {
    ...ri_fill,
    settings: "settings-rounded",
    widget: "widgets-rounded",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "edit-calendar",
    pin: "push-pin",
    sort: "sort-rounded",
    search: "search-rounded",
    checklist: "checklist-rounded",
    bookmark: "bookmark-rounded",
    edit: "edit",
    reset: "sync",
    delete_: "delete-rounded",
    menu: "menu-rounded",

    hide: "visibility-off",
    show: "visibility",
    space: "rocket-launch-rounded",
    add: "add-circle-rounded",
  },
  "material-symbols-light": {
    ...ri_line,
    settings: "settings-outline-rounded",
    widget: "widgets-outline-rounded",
    lock: "lock-outline",
    unlock: "lock-open-outline-rounded",
    habitTracker: "edit-calendar-outline-rounded",
    pin: "push-pin-outline",
    sort: "sort-rounded",
    search: "search",
    reset: "sync",
    checklist: "checklist-rounded",
    bookmark: "bookmark-outline-rounded",
    edit: "edit",
    delete_: "delete-outline-rounded",
    menu: "menu-rounded",

    hide: "visibility-off-outline",
    space: "rocket-launch-outline-rounded",
    show: "visibility-outline",
    add: "add-circle-outline-rounded",
  },
  tabler: {
    ...ri_line,
    settings: "settings",
    widget: "apps",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "calendar-check",
    pin: "pin",
    sort: "arrows-sort",
    search: "search",
    reset: "refresh",
    checklist: "list-check",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "menu",
    show: "eye",
    hide: "eye-off",
    space: "rocket",
    add: "square-rounded-plus",
  },
  lucide: {
    ...ri_line,
    settings: "settings",
    widget: "grid-2x2-plus",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "calendar-check",
    pin: "pin",
    search: "search",
    checklist: "list-check",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "menu",
    show: "eye",
    hide: "eye-off",
    space: "rocket",
    add: "circle-plus",
  },
  uil: {
    ...ri_line,
    settings: "setting",
    widget: "apps",
    lock: "lock",
    habitTracker: "calendar-alt",
    sort: "sort-amount-down",
    search: "search",
    reset: "refresh",
    checklist: "file-check-alt",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "bars",
    show: "eye",
    hide: "eye-slash",
    space: "rocket",
    add: "plus-circle",
  },
  carbon: {
    ...ri_line,
    settings: "settings",
    widget: "grid",
    lock: "locked",
    unlock: "unlocked",
    habitTracker: "calendar",
    pin: "pin",
    sort: "chevron-sort",
    search: "search",
    reset: "reset",
    checklist: "list-checked",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash-can",
    menu: "menu",
    space: "rocket",
    add: "add-alt",
  },
  hugeicons: {
    ...ri_line,
    settings: "settings-01",
    widget: "resources-add",
    lock: "circle-lock-01",
    unlock: "circle-unlock-01",
    habitTracker: "calendar-favorite-01",
    pin: "pin",
    sort: "sort-by-down-02",
    search: "search-01",
    reset: "refresh",
    checklist: "check-list",
    bookmark: "bookmark-02",
    edit: "edit-02",
    delete_: "delete-02",
    menu: "menu-01",
    show: "view",
    hide: "view-off",
    space: "rocket",
    add: "add-square",
  },
  "line-md": {
    ...ri_line,
    add: "plus-circle",
    checklist: "check-list-3-filled",
    menu: "menu",
    edit: "edit",
    sort: "filter-alt",
    show: "watch-loop",
    hide: "watch-off-loop",
    search: "search",
    settings: "cog-loop",
    space: "compass-loop",
    habitTracker: "calendar",
    bookmark: "star",
    reset: "backup-restore",
    delete_: "close-circle-filled",
    widget: <Icon icon="svg-spinners:blocks-scale" />,
  },
  "Solar Bold": { ...ri_fill, ...transformIcons(solar_bold, "solar") },
  "Solar Bold Duotone": {
    ...ri_fill,
    ...transformIcons(solar_bold, "solar", "bold", "bold-duotone"),
  },
  "Solar Line Duotone": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "line-duotone"),
  },
  "Solar Broken": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "broken"),
  },
  "Solar Line": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "linear"),
  },
};

export const chosenIcons = [
  "majesticons:book-open",
  "majesticons:bookmark",
  "majesticons:pin",
  "majesticons:hedset",
  "majesticons:heart",
  "majesticons:key",
  "majesticons:map-marker",
  "majesticons:microphone",
  "majesticons:music",
  "majesticons:music-note",
  "majesticons:phone",
  "majesticons:play-circle",
  "majesticons:question-circle",
  "majesticons:settings-cog",
  "majesticons:shopping-cart",
  "majesticons:skull",
  "majesticons:tag",
  "mage:chip-fill",
  "mage:dashboard-fill",
  "mage:rocket-fill",
  "mage:wrench-fill",
  "mage:trophy-fill",
  "ri:download-cloud-fill",
  "fluent:cloud-24-filled",
  "fluent:games-28-filled",
  "mingcute:game-2-fill",
  "fluent:board-games-20-filled",
  "fluent:video-32-filled",
  "jam:home-f",
];

export const IconPacks = [
  "oui",
  "dashicons",
  "icons8",
  "raphael",
  "flat-color-icons",
  "eva",
  "fe",
  "la",
  "gridicons",
  "maki",
  "zondicons",
  "el",
  "pixelarticons",
  "foundation",
  "fxemoji",
  "jam",
  "noto",
  "fluent-emoji-flat",
];

export const iconPackNames: Record<string, string> = {
  "material-symbols": "Material Symbols",
  "material-symbols-light": "Material Symbols Light",
  ic: "Google Material Icons",
  mdi: "Material Design Icons",
  ph: "Phosphor",
  solar: "Solar",
  tabler: "Tabler Icons",
  hugeicons: "Huge Icons",
  mingcute: "MingCute Icon",
  ri: "Remix Icon",
  bi: "Bootstrap Icons",
  carbon: "Carbon",
  iconamoon: "IconaMoon",
  iconoir: "Iconoir",
  ion: "IonIcons",
  lucide: "Lucide",
  "lucide-lab": "Lucide Lab",
  uil: "Unicons",
  tdesign: "TDesign Icons",
  teenyicons: "Teenyicons",
  clarity: "Clarity",
  bx: "BoxIcons",
  bxs: "BoxIcons Solid",
  majesticons: "Majesticons",
  "ant-design": "Ant Design Icons",
  lsicon: "Lsicon",
  gg: "css.gg",
  "gravity-ui": "Gravity UI Icons",
  octicon: "Octicons",
  memory: "Memory Icons",
  cil: "CoreUI Free",
  flowbite: "Flowbite Icons",
  mynaui: "Myna UI Icons",
  basil: "Basil",
  pixelarticons: "Pixelarticons",
  "akar-icons": "Akar Icons",
  ci: "coolicons",
  proicons: "ProIcons",
  "system-uicons": "System UIcons",
  typcn: "Typicons",
  "radix-icons": "Radix Icons",
  zondicons: "Zondicons",
  ep: "Element Plus",
  circum: "Circum Icons",
  "mdi-light": "Material Design Light",
  fe: "Feather Icon",
  "eos-icons": "EOS Icons",
  "bitcoin-icons": "Bitcoin Icons",
  charm: "Charm Icons",
  prime: "Prime Icons",
  humbleicons: "Humbleicons",
  uiw: "uiw icons",
  uim: "Unicons Monochrome",
  uit: "Unicons Thin Line",
  uis: "Unicons Solid",
  maki: "Maki",
  gridicons: "Gridicons",
  mi: "Mono Icons",
  cuida: "Cuida Icons",
  weui: "WeUI Icon",
  quill: "Quill Icons",
  "duo-icons": "Duoicons",
  gala: "Gala Icons",
  "lets-icons": "Lets Icons",
  f7: "Framework7 Icons",
  mage: "Mage Icons",
  marketeq: "Marketeq",
  fluent: "Fluent UI System Icons",
  "fluent-color": "Fluent UI System Color Icons",
  "icon-park-outline": "IconPark Outline",
  "icon-park-solid": "IconPark Solid",
  "icon-park-twotone": "IconPark TwoTone",
  "icon-park": "IconPark",
  jam: "Jam Icons",
  heroicons: "HeroIcons",
  pajamas: "Gitlab SVGs",
  "pepicons-pop": "Pepicons Pop!",
  "pepicons-print": "Pepicons Print",
  "pepicons-pencil": "Pepicons Pencil",
  bytesize: "Bytesize Icons",
  ei: "Evil Icons",
  streamline: "Streamline",
  guidance: "Guidance",
  "fa6-solid": "Font Awesome Solid",
  "fa6-regular": "Font Awesome Regular",
  ooui: "OOUI",
  "rivet-icons": "Rivet Icons",
  nimbus: "Nimbus",
  oui: "OpenSearch UI",
  formkit: "FormKit Icons",
  "line-md": "Material Line Icons",
  meteocons: "Meteocons",
  "svg-spinners": "SVG Spinners",
  openmoji: "OpenMoji",
  twemoji: "Twitter Emoji",
  noto: "Noto Emoji",
  "fluent-emoji": "Fluent Emoji",
  "fluent-emoji-flat": "Fluent Emoji Flat",
  "fluent-emoji-high-contrast": "Fluent Emoji High Contrast",
  "noto-v1": "Noto Emoji (v1)",
  emojione: "Emoji One (Colored)",
  "emojione-monotone": "Emoji One (Monotone)",
  "emojione-v1": "Emoji One (v1)",
  fxemoji: "Firefox OS Emoji",
  "streamline-emojis": "Streamline Emojis",
  bxl: "BoxIcons Logo",
  logos: "SVG Logos",
  "simple-icons": "Simple Icons",
  cib: "CoreUI Brands",
  "fa6-brands": "Font Awesome Brands",
  nonicons: "Nonicons",
  arcticons: "Arcticons",
  cbi: "Custom Brand Icons",
  brandico: "Brandico",
  "entypo-social": "Entypo+ Social",
  token: "Web3 Icons",
  "token-branded": "Web3 Icons Branded",
  cryptocurrency: "Cryptocurrency Icons",
  "cryptocurrency-color": "Cryptocurrency Color Icons",
  flag: "Flag Icons",
  "circle-flags": "Circle Flags",
  flagpack: "Flagpack",
  cif: "CoreUI Flags",
  gis: "Font-GIS",
  map: "Map Icons",
  geo: "GeoGlyphs",
  "vscode-icons": "VSCode Icons",
  codicon: "Codicons",
  "file-icons": "File Icons",
  devicon: "Devicon",
  "devicon-plain": "Devicon Plain",
  catppuccin: "Catppuccin Icons",
  "skill-icons": "Skill Icons",
  unjs: "UnJS Logos",
  "game-icons": "Game Icons",
  fad: "FontAudio",
  academicons: "Academicons",
  wi: "Weather Icons",
  healthicons: "Health Icons",
  "medical-icon": "Medical Icons",
  covid: "Covid Icons",
  la: "Line Awesome",
  eva: "Eva Icons",
  dashicons: "Dashicons",
  "flat-color-icons": "Flat Color Icons",
  entypo: "Entypo+",
  foundation: "Foundation",
  raphael: "Raphael",
  icons8: "Icons8 Windows 10 Icons",
  iwwa: "Innowatio Font",
  "heroicons-outline": "HeroIcons v1 Outline",
  "heroicons-solid": "HeroIcons v1 Solid",
  "fa-solid": "Font Awesome 5 Solid",
  "fa-regular": "Font Awesome 5 Regular",
  "fa-brands": "Font Awesome 5 Brands",
  fa: "Font Awesome 4",
  "fluent-mdl2": "Fluent UI MDL2",
  fontisto: "Fontisto",
  "icomoon-free": "IcoMoon Free",
  subway: "Subway Icon Set",
  oi: "Open Iconic",
  wpf: "Icons8 Windows 8 Icons",
  "simple-line-icons": "Simple line icons",
  et: "Elegant",
  el: "Elusive Icons",
  vaadin: "Vaadin Icons",
  "grommet-icons": "Grommet Icons",
  whh: "WebHostingHub Glyphs",
  "si-glyph": "SmartIcons Glyph",
  zmdi: "Material Design Iconic Font",
  ls: "Ligature Symbols",
  bpmn: "BPMN",
  "flat-ui": "Flat UI Icons",
  vs: "Vesper Icons",
  topcoat: "TopCoat Icons",
  il: "Icalicons",
  websymbol: "Web Symbols Liga",
  fontelico: "Fontelico",
  ps: "PrestaShop Icons",
  feather: "Feather Icons",
  "mono-icons": "Mono Icons",
  pepicons: "Pepicons",
};
